[build.environment]
  NODE_VERSION = "18"
  PNPM_FLAGS = "--no-frozen-lockfile"

[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = ".output/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
